language: java
matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: trusty
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
    - name: "MacOS JDK8"
      os: osx
      osx_image: xcode9.3
#    - name: "Windows" --- Not yet supported
#      os: windows
#      jdk:
#        - openjdk8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install ant; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD

script: 
  - ant test

before_deploy:
  - ant clean pack-with-funz
  - zip -r FunzTelemac.zip Funz*
  
deploy:
  provider: releases
  name: FunzTelemac
  api_key:
    secure: kUEnA9M8LoSU5Ps3X29Nobn2i/EuU6ogsJm+jEtUz8Uy/QA8YCMvAV8s01IIt+5aeIQlLFZA2AYWemVt3UwiBgBJvE4DqmuQF3yvAqJVD8w6qvuq9NqgVQ8ZYI2sMWYrOEjla7XVrRxYVbjCp1003WUfEx2d4flIb4qdg51WjVJ5hsIhX0aE4tKpFL9hlH4YtQ1YBRZGIhV3WCwCi44c4vlJEy2McnyUQJN4Stf0+QbvEoPQVwmr9IVuasmwvs1AQyBDFlE6CcD95R9vdlE2Lu1t2WDwHyX2ioSRFUS6VYMgCr2f88q1+oSoQCw3vJFuRGhYPVchcElyzunEDu4SLOH2YD9/QOPWTx8cfWy/mPZzVxB4jh4/lAs8CW22AFsEUWD2DJjO2Hx15WkWgHrN7L1kLijn+n8+9ayYd2TUKBgqYFVqV0M0B7cCQHktu6UhGjWmdW74bwiCwISxar9ph82cC5/sLOcSVhGz79I1iYZY8W+kH0lko1k6GUcbRLJ8OrZvd3WgF7hmvJeZWj4uI6yhzos1suY//GEH/r01UkVXfpNJs1u5boAHBeV0etFnoe1/Stgx2CqIRxjBffAgU1SjjoxcQ9U04HHjNxtSSzlyd/RYnRQ2S1iaxdvljhEF7J4XviEDdp1/ZEdPt0gHQeYM4kpDrhANK3CAaaxCrC0=
  file_glob: true
  file: Funz*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
